### ISSUE TITLE
Training and test files have to be real files

### ISSUE THREAD

**Issue by simon-clematide** [eske/word2vecpp-legacy#3]
Multivec just finishes training without an error exit code and stores a unusable model if the input files are only readable once, e.g. if the input is generated by some tools. There should be an error message.
The following shell command illustrates the point

 `multivec-bi --verbose --train-src <(zcat UNv1.0.en-es.en.gz |  tr -d '“[:punct:]”' )  --train-trg <(zcat UNv1.0.en-es.es.gz |  tr -d '[:punct:]')`

**Comment by alex-berard** [comment]
Hello Simon,

What actually happens when training with this kind of file is that:
- MultiVec reads the training file once to build the vocabulary, and model weights are initialized at random.
- When MultIvec tries to read the file for training, it finds an empty file (because it was consumed by the previous step), so the initial weights are not updated at all.
- Saving works fine since vocabulary and weights are OK, but you get random weights.

I just committed a solution to this problem, that checks if the training file is empty before starting training, and throws an exception if that is the case.

**Comment by simon-clematide** [comment]
Thanks. That's a reasonable behavior.
